
spring:
  application: 
    name: CONFIG-SERVER-DEV

# eureka client configuration
  eureka:
    instance:
      prefer-ip-address: true

    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
